USE ROLE &ADMIN_ROLE;
USE WAREHOUSE &WAREHOUSE;
USE DATABASE &CURATED_DB;
USE SCHEMA &CUSTOMER_VIEW_SCHEMA;

create or replace view VW_IEDR_ACCOUNT_METADATA(
BILLING_ACCOUNT_NBR,
ACCOUNT_NAME,
ACCOUNT_STATUS,
ACCOUNT_TYPE,
ACCOUNT_PHONE_NBR,
EMAIL_ADDRESS,
MAILING_ADDRESS,
ACCOUNT_START_DT,
ACCOUNT_END_DT
) as(
 WITH
CTE_CIS00928 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS00928'),
CTE_CIS05039 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS05039')
SELECT DISTINCT A.KY_BA AS BILLING_ACCOUNT_NBR,
I.NM_COMPRESSED AS ACCOUNT_NAME,
E.DESCRIPTION AS ACCOUNT_STATUS,
H.DESCRIPTION AS ACCOUNT_TYPE,
CASE WHEN LENGTH(TRIM(I.TX_HOME_ACD)) >0 AND I.TX_HOME_ACD != '000' THEN (I.TX_HOME_ACD ||'-'
||I.TX_HOME_PHN_NO)
ELSE '' END AS ACCOUNT_PHONE_NBR,
 case when TRIM(B.tx_prof_email) is null then ' ' else TRIM(B.tx_prof_email) end as
EMAIL_ADDRESS,
 I.AD_COMPRESSED AS MAILING_ADDRESS,
 TO_TIMESTAMP(A.DT_BA_OPEN) AS ACCOUNT_START_DT,
 CASE
 WHEN A.DT_BA_TERM >= TO_DATE('9999-12-31')
 OR A.DT_BA_TERM = TO_DATE('0001-01-01') THEN ' '
 ELSE TO_CHAR(TO_TIMESTAMP_TZ(A.DT_BA_TERM))
 END AS ACCOUNT_END_DT
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU02TB01_BILL_ACCT A
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU01TB01_SAD I ON A.KY_BA = I.KY_BA AND A.KY_PREM_NO = I.
KY_PREM_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON A.KY_PREM_NO = C.KY_PREM_NO
 LEFT OUTER JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU16TB04_PROF_BA D ON A.KY_BA = D.KY_BA
 LEFT OUTER JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU16TB02_PROFILE B ON D.KY_PROFILE_ID = B.KY_PROFILE_ID
 JOIN CTE_CIS00928 E ON A.CD_BA_STAT = E.CODE
 JOIN CTE_CIS05039 H ON A.CD_RES_COMM = H.CODE
 WHERE C.CD_PREM_STAT = '02' AND (B.cd_profile_type='W' or B.ky_profile_id is null) and (D.cd_stat
=2 or D.ky_ba is null)
 AND TRIM(I.AD_SERV_ST) = 'NY'
 GROUP BY 1,2,3,4,5,6,7,8,9);

 create or replace view VW_IEDR_ACCOUNT_TO_SERVICE_AGREEMENT(
 ACCOUNT_ID,
 SERVICE_TYPE,
 START_DATE,
 END_DATE
 ) as (
 WITH CTE_CIS1081 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS01081' AND TRIM(CODE) IN ('0100','0200'))
 SELECT DISTINCT A.KY_BA as ACCOUNT_ID,TRIM(D.DESCRIPTION) AS SERVICE_TYPE,
 A.DT_BA_OPEN AS START_DATE,A.DT_BA_TERM AS END_DATE
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU02TB01_BILL_ACCT A
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU02TB04_DB_ACTVTY B ON A.KY_BA = B.KY_BA
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON A. KY_PREM_NO = C.KY_PREM_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU01TB01_SAD E ON A.KY_BA = E.KY_BA AND A.KY_PREM_NO= E.KY_PREM_NO
 JOIN CTE_CIS1081 D ON B.CD_BUS = D.CODE
 WHERE C.CD_PREM_STAT = '02' AND TRIM(E.AD_SERV_ST) = 'NY' GROUP BY 1,2,3,4);
 create or replace view VW_IEDR_BILLING_ACCOUNT_TO_SERVICE_POINT_ELECTRIC(
 BILLING_ACCOUNT_NUMBER,
 SERVICE_POINT_ID,
 PREMISE_ID,
 START_DATE,
 END_DATE
 ) as (
 SELECT M.BILLING_ACCOUNT_NUMBER,M.GIS_SERVICE_ID AS SERVICE_POINT_ID,M.PREMISE_NUMBER AS
PREMISE_ID,
 TO_TIMESTAMP_TZ(MPT.dt_set_cmplt) AS START_DATE,
 CASE WHEN MPT.dt_remv_cmplt >= TO_DATE('9999-12-31') THEN ' '
 ELSE TO_CHAR(TO_TIMESTAMP_TZ(MPT.dt_remv_cmplt)) END AS END_DATE
 FROM &EDM_DB.&EDA_SCHEMA.METER_TO_PREMISE M
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON M.PREMISE_NUMBER = C.KY_PREM_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB49_METER_PT MPT ON MPT.KY_PREM_NO=C.KY_PREM_NO
 WHERE C.CD_PREM_STAT = '02' AND TRIM(M.STATE) = 'NY' AND TRIM(M.ACCOUNT_STATUS) = 'Active' AND
TRIM(M.STATE) = 'NY'
 GROUP BY 1,2,3,4,5);

 create or replace view VW_IEDR_BILLING_ACCOUNT_TO_SERVICE_POINT_GAS(
 BILLING_ACCOUNT_NUMBER,
 SERVICE_POINT_ID,
 PREMISE_ID,
 START_DATE,
 END_DATE
 ) as (
 SELECT SPT.KY_BA AS BILLING_ACCOUNT_NUMBER,MG.SERVICEPOINT_ID AS SERVICE_POINT_ID,MG.PREMISE_ID
AS PREMISE_ID,
 TO_TIMESTAMP_TZ(MPT.dt_set_cmplt) AS START_DATE,
 CASE WHEN MPT.dt_remv_cmplt >= TO_DATE('9999-12-31') THEN ' '
 ELSE TO_CHAR(TO_TIMESTAMP_TZ(MPT.dt_remv_cmplt)) END AS END_DATE
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU04TB03_SERVC_PT SPT
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB49_METER_PT MPT ON MPT.ky_spt = SPT.KY_SPT AND MPT.
KY_PREM_NO=SPT.KY_PREM_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON MPT.KY_PREM_NO=C.KY_PREM_NO
 JOIN &GDM_DB.&GDA_SCHEMA.VW_IEDR_GAS_METER_SERVICEPOINT MG ON MG.PREMISE_ID = C.KY_PREM_NO
 WHERE C.CD_PREM_STAT = '02' AND TRIM(MG.STATE) = 'NY' AND TRIM(SPT.IUDL_IND) <> 'D' AND TRIM(
MPT.IUDL_IND) <> 'D'
 GROUP BY 1,2,3,4,5) ;

 create or replace view VW_IEDR_BILL_DATA(
 BILL_ID,
 ACCOUNT_ID,
 CUSTOMER_ID,
 ACCOUNT_STATUS,
 BILLING_ADDRESS,
 STATEMENT_DATE,
 BILL_AMOUNT_DUE,
 BILL_DUE_DATE,
 SERVICE_TYPE,
 SERVICE_CLASS,
 TARIFF_TYPE,
 SERVICE_USAGE,
 SERVICE_UNITS,
 SERVICE_SUPPLIER_ID,
 SERVICE_SUPPLIER_NAME,
 SERVICE_SUPPLIER_TARIFF,
 BILLING_PERIOD_DAYS
 ) as(
 WITH cte_cis1081 AS (SELECT TRIM(code) AS code,description FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE cisname = 'CIS01081'),
 cte_cis33626 AS (SELECT TRIM(code) AS code,description FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE cisname = 'CIS33626'AND TRIM(CODE) IN ('010', '090')),
 cte_cis00928 AS (SELECT TRIM(code) AS code,description FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE cisname = 'CIS00928'),
 cte_CIS00225 AS (SELECT TRIM(code) AS code,description FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE cisname = 'CIS00225'),
 cte_CIS04180 AS (SELECT TRIM(code) AS code,description FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE cisname = 'CIS04180'),
 cte_usage AS (
 SELECT DISTINCT
 DEBT.KY_BA || DEBT.DT_DB || DEBT.CD_BUS as bill_id,
 -- this is an alternate key
 DEBT.KY_BA As account_id,
 BAC.KY_CUST_NO AS Customer_id,
 cte_cis00928.description AS account_status,
 SAD.AD_COMPRESSED AS billing_address,
 TO_TIMESTAMP_TZ(DEBT.DT_DB) AS Statement_date,
 TO_TIMESTAMP_TZ(BILLH.DT_DUE) As bill_due_date,
 cte_cis1081.description AS service_type,
 cte_CIS00225.description AS service_class,
 cte_CIS04180.description AS tariff_type,
 USG.QY_TOT_USAGE_1 AS service_usage,
 cte_cis33626.description AS service_units,
 D.CD_SERV_SUPP AS Service_Supplier_ID,
 E.TX_SERV_SUPP AS Service_Supplier_Name,
 F.CD_TAR_SCH as Service_Supplier_Tariff,
 BILLH.QY_DA_USE AS Billing_Period_Days
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU02TB04_DB_ACTVTY DEBT
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU12TB01_BILL_HDR BILLH ON BILLH.KY_BA = DEBT.KY_BA AND DEBT
.DT_BILL = BILLH.DT_BILL_TO_CUST
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU02TB01_BILL_ACCT BAC ON BAC.KY_BA = DEBT.KY_BA--AND
BAC.CD_BA_STAT = '02'
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB20_TOTUSGHDR USG ON DEBT.KY_BA = USG.KY_BA AND BAC.
KY_PREM_NO = USG.KY_PREM_NO AND USG.KY_SPT = DEBT.KY_PROD_ORDNO AND DEBT.DT_STAT = USG.
DT_ROW_STAT
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU01TB01_SAD SAD ON BAC.KY_BA = SAD.KY_BA AND BAC.KY_PREM_NO
= SAD.KY_PREM_NO --AND BAC.KY_AD = SAD.KY_AD
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON USG. KY_PREM_NO = C.KY_PREM_NO
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB03_SERVC_PT F ON F.KY_BA = DEBT.KY_BA AND F.
KY_PREM_NO = SAD.KY_PREM_NO AND F.KY_SPT = DEBT.KY_PROD_ORDNO
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU12TB51_PRICE_USG D ON BAC.KY_PREM_NO = D.KY_PREM_NO
AND D.KY_SPT = DEBT.KY_PROD_ORDNO AND DEBT.KY_BA = D.KY_BA AND D.CD_PU_REC_TYPE ='01'
--AND D.CD_PU_STATUS ='01'
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU05TB74_MARKETER E ON TRIM(D.CD_SERV_SUPP) = TRIM(E.
CD_SERV_SUPP)
 JOIN cte_cis1081 ON cte_cis1081.code = DEBT.CD_BUS
 JOIN cte_cis33626 ON cte_cis33626.code = USG.CD_USAGE_TYPE_1
 JOIN cte_cis00928 ON cte_cis00928.code = BAC.CD_BA_STAT
 JOIN cte_CIS00225 ON cte_CIS00225.code = USG.CD_TAR_SCH
 JOIN cte_CIS04180 ON cte_CIS04180.code = BAC.CD_TAR_TYPE
 WHERE DEBT.CD_DB_SRCE = 'B' -- B for Billing
 -- Fluke or design ?--AND USG.KY_SPT = DEBT.KY_PROD_ORDNO -- AND DEBT.KY_BA = USG.KY_BA
 AND DEBT.DT_BILL > DATEADD(month, -12, CURRENT_DATE())
 AND USG.DT_RDG_TO > DATEADD(month, -12, CURRENT_DATE())
 AND C.CD_PREM_STAT = '02'
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
 )
 SELECT * FROM cte_usage ORDER BY ACCOUNT_ID DESC);

 create or replace view VW_IEDR_BUILDING_TO_SERVICE_POINT_ELECTRIC(
 SERVICE_POINT_ID,
 PREMISE_ID,
 BUILDING_ID,
 BUILDING_ID_TYPE
 ) as(
 SELECT M.GIS_SERVICE_ID AS SERVICE_POINT_ID,M.PREMISE_NUMBER AS PREMISE_ID,
 PRM.KY_BLDG_NO AS BUILDING_ID,
 BT.DESCRIPTION AS BUILDING_ID_TYPE
 FROM &EDM_DB.&EDA_SCHEMA.METER_TO_PREMISE M
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE PRM ON PRM.KY_PREM_NO = M.PREMISE_NUMBER
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB57_BUILDING BLD ON BLD.KY_BLDG_NO=PRM.KY_BLDG_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.VW_CD_BLDG_TYPE BT ON TRIM(BLD.CD_BLDG_TYPE)=TRIM(BT.CODE)
 WHERE PRM.CD_PREM_STAT = '02' AND TRIM(M.STATE) = 'NY'
 GROUP BY 1,2,3,4 );

 create or replace view VW_IEDR_BUILDING_TO_SERVICE_POINT_GAS(
 SERVICE_POINT_ID,
 PREMISE_ID,
 BUILDING_ID,
 BUILDING_ID_TYPE
 ) as(
 SELECT MG.SERVICEPOINT_ID AS SERVICE_POINT_ID,MG.PREMISE_ID AS PREMISE_ID,
 PRM.KY_BLDG_NO AS BUILDING_ID,
 BT.DESCRIPTION AS BUILDING_ID_TYPE
 FROM &GDM_DB.&GDA_SCHEMA.VW_IEDR_GAS_METER_SERVICEPOINT MG
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE PRM ON PRM.KY_PREM_NO = MG.PREMISE_ID
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB57_BUILDING BLD ON BLD.KY_BLDG_NO=PRM.KY_BLDG_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.VW_CD_BLDG_TYPE BT ON TRIM(BLD.CD_BLDG_TYPE)=TRIM(BT.CODE)
 WHERE PRM.CD_PREM_STAT = '02' AND TRIM(MG.STATE) = 'NY'
 GROUP BY 1,2,3,4 );

 create or replace view VW_IEDR_CUSTOMER_METADATA(
 CUSTOMER_ID,
 CUSTOMER_NAME,
 ACCOUNT_PHONE_NBR,
 EMAIL_ADDRESS,
 POSTAL_ADDRESS,
 CUSTOMER_REGISTERED_AT,
 CUSTOMER_CLOSED_AT
 ) as(
 WITH CTE_CIS1081 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS01081' AND TRIM(CODE) IN ('0100','0200'))
 SELECT DISTINCT A.KY_CUST_NO AS CUSTOMER_ID,A.NM_COMPRESSED AS CUSTOMER_NAME,
 CASE WHEN LENGTH(TRIM(E.TX_HOME_ACD)) > 0
 AND E.TX_HOME_ACD != '000' THEN (E.TX_HOME_ACD || '-' || E.TX_HOME_PHN_NO)
 ELSE '' END AS ACCOUNT_PHONE_NBR,TRIM(D.TX_PROF_EMAIL)AS EMAIL_ADDRESS,A.AD_COMPRESSED AS
POSTAL_ADDRESS ,
 E.DT_CUST_STAT AS CUSTOMER_REGISTERED_AT, ' ' AS CUSTOMER_CLOSED_AT
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU01TB01_SAD A
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU16TB04_PROF_BA B ON A.KY_BA = B.KY_BA
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU16TB02_PROFILE D ON B.KY_PROFILE_ID = D.KY_PROFILE_ID AND B.
CD_STAT = 2 AND D.CD_PROFILE_TYPE = 'W'
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU03TB01_CUSTOMER E ON A.KY_CUST_NO = E.KY_CUST_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON A. KY_PREM_NO = C.KY_PREM_NO
 WHERE C.CD_PREM_STAT = '02'AND TRIM(A.AD_SERV_ST) = 'NY' GROUP BY 1,2,3,4,5,6,7);

 create or replace view VW_IEDR_INTERVAL_DATA_ELECTRIC(
 METER_ID,
 CHANNEL,
 TIMESTAMP,
 DURATION_IN_DAYS,
 VALUE,
 UNITS,
 QUALITY
 ) as (
 SELECT DISTINCT
 METER_ID, CHANNEL, TIMESTAMP, DURATION_IN_DAYS, VALUE, UNITS, QUALITY
 FROM (SELECT
 METER.METER_NUMBER AS METER_ID, METER.METER_CHANNEL AS CHANNEL, INT.TM_START AS TIMESTAMP,
INT.DURATION_IN_DAYS AS DURATION_IN_DAYS, INT.QY_INTRVL_DATA_1 AS VALUE,
 INT.UNITS AS UNITS, INT.QUALITY AS QUALITY
 FROM ((SELECT
 METER_NUMBER, METER_CHANNEL, PREMISE_NUMBER,
 CURRENT_USER() AS NGLOADEDBY,
 CURRENT_TIMESTAMP() AS NGLOADDATE,
 CURRENT_TIMESTAMP() AS NGMODDATE
 FROM ((SELECT DISTINCT
 METER_NUMBER, METER_CHANNEL, PREMISE_NUMBER
 FROM ((SELECT
 METER_NUMBER, METER_CHANNEL, PREMISE_NUMBER
 FROM &EDM_DB.&EDA_SCHEMA.METER_TO_PREMISE)))))) AS METER
 LEFT OUTER JOIN
 ((SELECT KY_MTR_EQUIP_NO, CD_INTRVL_TYPE, QY_INTRVL_DATA_1, TM_START, QY_INTRVL_CNTR,
CD_FREQ_INTRVL,
 Case
 When CD_INTRVL_TYPE = '1' then 'KW'
 When CD_INTRVL_TYPE = '2' then 'KVA'
 When CD_INTRVL_TYPE = '3' then 'KVAR'
 When CD_INTRVL_TYPE = '4' then 'VOLTA-SQR-PER-HOUR'
 When CD_INTRVL_TYPE = '5' then 'VDER'
 END AS UNITS,
 '1' AS DURATION_IN_DAYS, QY_INTRVL_DATA_1AS VALUE, 'RAW'AS QUALITY
 FROM ((SELECT DISTINCT
 KY_MTR_EQUIP_NO, CD_INTRVL_TYPE, QY_INTRVL_DATA_1, TM_START, QY_INTRVL_CNTR, CD_FREQ_INTRVL
 FROM ((SELECT
 KY_MPT_NO, KY_MTR_EQUIP_NO, DT_INTRVL_RDG, TM_START, CD_INTRVL_TYPE, CD_INTRVL_SRCE,
KY_TEST_ID, CD_FREQ_INTRVL, QY_INTRVL_CNTR, CD_DST_TYPE, CD_RDG_STAT, TS_KY_TOT,
 QY_INTRVL_DATA_1, CD_INTRVL_STAT_1, QY_INTRVL_DATA_2, QY_INTRVL_DATA_3, QY_INTRVL_DATA_9
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU04TB14_INTERVAL)))))) AS INT
 ON METER.METER_NUMBER=INT.KY_MTR_EQUIP_NO));

 create or replace view VW_IEDR_INTERVAL_DATA_GAS(
 METER_ID,
 CHANNEL,
 TIMESTAMP,
 DURATION_IN_DAYS,
 VALUE,
 QUALITY
 ) as (
 select SPM.meter_id as meter_id, '' as channel , R.DT_RDG_FROM as timestamp, DATEDIFF(day, R.
DT_RDG_FROM::DATE, R.DT_RDG_TO::DATE) as duration_in_days, R.QY_TOT_USAGE_1
 as value, 'RAW' as quality from &GDM_DB.&GDA_SCHEMA.VW_IEDR_GAS_METER_SERVICEPOINT SPM
 left join &CDP_DB.&CSS_CDP_SCHEMA.CU04TB20_TOTUSGHDR R on R.ky_prem_no = SPM.PREMISE_ID
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON SPM.PREMISE_ID = C.KY_PREM_NO
 where CD_USAGE_TYPE_1 = '090' and SPM.STATE = 'NY' AND C.CD_PREM_STAT = '02'
 GROUP BY 1,2,3,4,5,6);

 create or replace view VW_IEDR_METER_METADATA_ELECTRIC(
 PREMISE_ID,
 METER_ID,
 METER_NUMBER,
 METER_TYPE,
 METER_STATUS,
 METER_CHANNEL,
 METER_PROPERTY,
 INSTALLED_AT,
 REMOVED_AT,
 CREATED,
 UPDATED
 ) as (
 select M.PREMISE_NUMBER AS PREMISE_ID,M.METER_NUMBER AS METER_ID,M.METER_NUMBER ,M.METER_TYPE,M.
METER_STATUS,M.METER_CHANNEL,M.METER_PROPERTY, M.INSTALLED_AT,M.REMOVED_AT,M.CREATED,M.UPDATED
 from &EDM_DB.&EDA_SCHEMA.METER_TO_PREMISE M
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON M.PREMISE_NUMBER = C.KY_PREM_NO
 WHERE M.STATE = 'NY' AND C.CD_PREM_STAT = '02' GROUP BY 1,2,3,4,5,6,7,8,9,10,11);

 create or replace view VW_IEDR_METER_METADATA_GAS(
 PREMISE_ID,
 METER_NUMBER,
 METER_TYPE,
 METER_STATUS,
 METER_CHANNEL,
 METER_PROPERTY,
 INSTALLED_AT,
 REMOVED_AT,
 CREATED,
 UPDATED
 ) as (
 select
 SP.PREMISE_ID,
 SP.meter_id as METER_NUMBER,
 SP.METER_TYPE,
 SP.METER_STATUS,
 '' AS METER_CHANNEL,
 '' as METER_PROPERTY,
 SP.meter_connection_start_time as INSTALLED_AT,
 SP.meter_connection_end_time as REMOVED_AT,
 CURRENT_TIMESTAMP as CREATED,
 CURRENT_TIMESTAMP as UPDATED
 from &GDM_DB.&GDA_SCHEMA.VW_IEDR_GAS_METER_SERVICEPOINT SP
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON SP.PREMISE_ID = C.KY_PREM_NO
 where SP.STATE = 'NY' AND C.CD_PREM_STAT = '02'
 GROUP BY 1,2,3,4,5,6,7,8,9);

 create or replace view VW_IEDR_RATE_PLAN_METADATA(
 COUNT(*),
 DATE_CANCELLATION,
 DATE_DRAFT_UPDATE,
 DATE_EFFECTIVE_PRCS,
 RATE_CODE,
 RATE_PLAN_CODE_UNIQUE,
 RATE_PLAN_DESCRIPTION,
 RATE_PLAN_HAS_DEMANDCHARGES,
 RATE_PLAN_HAS_ICAPTAG,
 RATE_PLAN_HAS_REACTIVEPOWER,
 RATE_PLAN_HAS_TIMEOFUSE_PRICING,
 COMPANY_CODE,
 RATE_PLAN_IEDR_ORG_ABBREVIATION,
 RATE_PLAN_NAME,
 SEASN_PEAK,
 SEASN_TM_INT_START,
 SEASN_TM_INT_END,
 SEASN_SUMR_WIN,
 DT_SEAS_BEG,
 DT_SEAS_END,
 RATE_PLAN_HAS_RETAILSUPPLY,
 RATE_PLAN_TARIFF_ID,
 RATE_PLAN_TERRITORY,
 SC_CUSTOMERCLASS,
 SC_SERVICECLASS_NAME,
 SC_SERVICECLASS_NUMBER,
 SC_SERVICETYPE,
 TARIFF_DPS_CASENUMBER,
 TARIFF_UTILITY_NAME,
 TARIFF_UTILITY_PSCNUMBER
 ) as
 WITH CTE_CIS04569 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS04569'),
.CSSCODES WHERE CISNAME = 'CIS43376'),
 CTE_CIS04180 AS (SELECT /* CD_TAR_TYPE */ TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&
CSS_CDP_SCHEMA.CSSCODES WHERE CISNAME = 'CIS04180'),
 CTE_CIS00059 AS (SELECT TRY_TO_NUMBER(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.
CSSCODES WHERE CISNAME = 'CIS00059'),
 RPC AS (
 SELECT COUNT(*),
 CASE WHEN tarschedrate.DT_TERM = '9999-12-31' THEN TO_DATE(NULL)
 ELSE tarschedrate.DT_TERM END AS date_cancellation,
 'From the Rate Book for a tariff' AS date_draft_update,
 tarschedrate.DT_EFF_PRCS AS date_effective_prcs,
 tarsched.CD_TAR_RT_CL AS rate_code,
 tarsched.TX_TAR_SHORT_DESC AS rate_plan_code_unique,
 tarsched.TX_TAR_SCH_BP_DESC AS rate_plan_description,
 CASE WHEN tarsched.FL_DEM = 'N' THEN 'False'
 WHEN tarsched.FL_DEM = 'Y' THEN 'True'
 ELSE 'TBD'
 END rate_plan_has_demandcharges,
 'Likely False' as rate_plan_has_icaptag,
 'Likely False' as rate_plan_has_reactivepower,
 CASE WHEN tarsched.TX_TAR_SCH_DESC LIKE 'Electric%' THEN 'False'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE 'Gas%'
 AND CD_CONS_CL > '00' THEN 'True'
 ELSE 'False' END rate_plan_has_tiered_blocks,
 CASE
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%TOU%' THEN 'True'
 ELSE 'False'
 END rate_plan_has_timeofuse_pricing,
 tarsched.CD_CO AS company_code,
 CASE
 WHEN tarsched.CD_CO = '0037' THEN 'KLI'
 WHEN tarsched.CD_CO = '0012' THEN 'NIM'
 END as rate_plan_iedr_org_abbreviation,
 CASE WHEN seasn.cd_rider = '00' THEN 'False'
 ELSE 'True' END rate_plan_is_raterider,
 tarsched.tx_tar_sch_desc AS rate_plan_name,
 CASE WHEN seasn.cd_peak = '02' then 'Off Peak'
 WHEN seasn.cd_peak ='01' then 'On Peak'
 WHEN seasn.cd_peak = '00' then 'Total'
 ELSE 'Other Code - '||seasn.cd_peak
 END as Seasn_peak,
 seasn.tm_int_start AS seasn_tm_int_start,
 seasn.tm_int_end AS seasn_tm_int_end,
 CASE
 WHEN seasn.cd_sumr_win = 'B' then 'All Year'
 WHEN seasn.cd_sumr_win = 'S' then 'Summer'
 ELSE 'Other Code - '||seasn.cd_sumr_win
 END AS seasn_sumr_win,
 seasn.DT_SEAS_BEG,
 seasn.DT_SEAS_END,
 -- seasn.No_sequence AS seasn_No_sequence,
 'TBD' AS rate_plan_nbr_periods,
 CASE
 WHEN tarsched.cd_tar_svc_type = '11' THEN 'True'
 ELSE 'False'
 END as rate_plan_has_retailsupply,
 tarsched.cd_tar_sch AS rate_plan_tariff_id,
 'all' AS rate_plan_territory,
 -- cte_CIS04180.description as sc_customerclass,
 CASE
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Elec%' THEN 'Electric'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Gas%' THEN 'Gas'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Light%' THEN 'Lighting'
 ELSE 'TBD'
 END AS sc_customerclass,
 tarsched.TX_TAR_SHORT_DESC as sc_serviceclass_name,
 tarsched.TX_TAR_SCH_DESC AS sc_serviceclass_number,
 CASE
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Elec%' THEN 'Electric'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Gas%' THEN 'Gas'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Light%' THEN 'Lighting'
 ELSE 'TBD'
 END AS sc_servicetype,
 'TBD' as tariff_dps_casenumber,
 CTE_CIS00059.description AS tariff_utility_name,
 CASE WHEN tarsched.CD_CO = '0012' -- Niagara Mohawk (NMI)
 THEN
 CASE WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Elec%' THEN '220'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Gas%' THEN '219'
 WHEN tarsched.TX_TAR_SCH_DESC LIKE '%Light%' THEN '214'
 ELSE 'TBD' END
 ELSE
 CASE WHEN tarsched.CD_CO = '0037' -- (KLI)
 THEN '1'
 ELSE 'TBD'
 END
 END tariff_utility_pscnumber

 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU12TB20_TARSCHRTE tarschedrate
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB05_TAR_SCH tarsched ON
 tarschedrate.CD_TAR_SCH = tarsched.CD_TAR_SCH
 AND tarschedrate.CD_CO = tarsched.CD_CO
 JOIN CTE_CIS00059 ON tarschedrate.CD_CO = CTE_CIS00059.code
 JOIN CTE_CIS04569 ON tarsched.CD_TAR_RT_CL = CTE_CIS04569.code
 -- JOIN cte_CIS04180 ON cte_CIS04180.code = tarsched.CD_TAR_SCH
 JOIN CTE_CIS43376 ON CTE_CIS43376.code = tarsched.CD_TAR_SVC_TYPE
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB10_SEASNPEAK seasn ON
 seasn.CD_TAR_SCH = TARSCHED.CD_TAR_SCH
 AND seasn.CD_CO = TARSCHED.CD_CO
 WHERE 1=1

 --AND seasn.DT_EFF = tarschedrate.DT_EFF_PRCS
 AND TARSCHED.CD_CO IN ( 12, 37)
 -- AND CTE_CIS43376.description <> 'NY Transition and Delete'
 AND (
 ( tarsched.TX_TAR_SCH_DESC LIKE 'Electric%' AND tarschedrate.DT_EFF_PRCS >=
'2022-12-31')
 OR
 ( tarsched.TX_TAR_SCH_DESC LIKE 'Gas%' AND tarschedrate.DT_EFF_PRCS >= '2023-06-01')
 )
 GROUP BY 2,3,4,5,6,7,8,9,10,11,12,13,14,15, 16,17,18,19,20,
 21, 22,23,24,25,26,27,28, 29,30,31,32
 ORDER BY 4 DESC
 )
 SELECT * FROM RPC;

 create or replace view VW_IEDR_SERVICE_AGREEMENT_METADATA(
 BILLING_ACCOUNT_ID,
 ACCOUNT_STATUS,
 SERVICE_TYPE,
 SERVICE_CLASS,
 SERVICE_PROPERTY,
 SERVICE_ADDRESS,
 RATE_PLAN,
 RATE_MODIFIER,
 SUPPLIER_ID,
 SUPPLIER_NAME,
 SUPPLIER_RATE_PLAN,
 ACCOUNT_START_DT,
 ACCOUNT_END_DT
 WITH CTE_CIS1081 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS01081' AND TRIM(CODE) IN ('0100','0200')),
 CTE_CIS00928 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS00928'),
 CTE_CIS00225 AS (SELECT TRIM(CODE) AS CODE,DESCRIPTION FROM &CDP_DB.&CSS_CDP_SCHEMA.CSSCODES
WHERE CISNAME = 'CIS00225')
 SELECT DISTINCT A.KY_BA AS BILLING_ACCOUNT_ID,
 E.DESCRIPTION AS ACCOUNT_STATUS,
 D.DESCRIPTION AS SERVICE_TYPE,
 G.DESCRIPTION AS SERVICE_CLASS,
 M.CD_RIDER AS service_property,
 SD.AD_COMPRESSED AS service_address ,
 SPT.CD_TAR_SCH as RATE_PLAN,
 J.CD_RIDER AS rate_modifier,
 PR.CD_SERV_SUPP AS supplier_id,
 MK.TX_SERV_SUPP AS supplier_name ,
 A.DT_BA_OPEN AS ACCOUNT_START_DT,
 CASE WHEN A.DT_BA_TERM >= TO_DATE('9999-12-31') OR A.DT_BA_TERM = TO_DATE('0001-01-01') THEN ' '
ELSE TO_CHAR(TO_TIMESTAMP_TZ(A.DT_BA_TERM))END AS ACCOUNT_END_DT
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU02TB01_BILL_ACCT A
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU02TB04_DB_ACTVTY B ON A.KY_BA = B.KY_BA
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON A. KY_PREM_NO = C.KY_PREM_NO
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU01TB01_SAD SD ON A.KY_BA =SD.KY_BA AND A.KY_PREM_NO = SD.
KY_PREM_NO
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB03_SERVC_PT SPT ON SPT.KY_BA = A.KY_BA AND SPT.KY_PREM_NO
= A.KY_PREM_NO AND SPT.KY_SPT = B.KY_PROD_ORDNO
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU12TB51_PRICE_USG PR ON PR.KY_SPT = B.KY_PROD_ORDNO AND A.
KY_PREM_NO = PR.KY_PREM_NO AND A.KY_BA = PR.KY_BA AND PR.CD_PU_REC_TYPE ='01'--AND
PR.CD_PU_STATUS ='01'
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU05TB74_MARKETER MK ON TRIM(PR.CD_SERV_SUPP) = TRIM(MK.
CD_SERV_SUPP)
 --LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB05_TAR_SCH I ON I.CD_TAR_SCH = SPT.CD_TAR_SCH AND
I.CD_CO = A.CD_CO --AND I.CD_CO = SD.CD_CO
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB49_METER_PT MP ON MP.KY_PREM_NO = A.KY_PREM_NO AND MP.
KY_SPT = B.KY_PROD_ORDNO
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU02TB37_CONTRACTS J ON A.KY_PREM_NO = J.KY_PREM_NO AND J.
KY_SPT = B.KY_PROD_ORDNO AND J.CD_TAR_SCH = SPT.CD_TAR_SCH --AND TRIM(A.KY_BA) = TRIM(J.KY_BA) --
 LEFT JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU02TB57_SV_DP_CNT M on M.KY_SERVICE_DROP = MP.KY_SERVICE_DROP
 JOIN CTE_CIS1081 D ON B.CD_BUS = D.CODE
 JOIN CTE_CIS00225 G ON G.CODE = SPT.CD_TAR_SCH
 WHERE C.CD_PREM_STAT = '02'
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13--,14,15,16
 ORDER BY 1
 );

 create or replace view VW_IEDR_SERVICE_POINT_METADATA_ELECTRIC(
 SERVICE_POINT_NUMBER,
 PREMISE_ID,
 SERVICE_POINT_NAME,
 STREET_NUMBER,
 STREET_NAME,
 TOWN_NAME,
 STATE,
 ZIP_CODE,
 SERVICE_POINT_ADDRESS,
 INSTALLED_AT,
 REMOVED_AT,
 CREATED,
 UPDATED
 ) as (
 select M.GIS_SERVICE_ID AS SERVICE_POINT_NUMBER,M.PREMISE_NUMBER as PREMISE_ID,M.
SERVICE_POINT_NAME,M.STREET_NUMBER,M.STREET_NAME,M.TOWN_NAME,M.STATE, M.ZIP_CODE,
 M.SERVICE_ADDRESS AS SERVICE_POINT_ADDRESS,M.INSTALLED_AT,M.REMOVED_AT,M.CREATED,M.UPDATED
 from &EDM_DB.&EDA_SCHEMA.METER_TO_PREMISE M
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON M.PREMISE_NUMBER = C.KY_PREM_NO
 WHERE M.STATE = 'NY' AND C.CD_PREM_STAT = '02' GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13)
 ;

 create or replace view VW_IEDR_SERVICE_POINT_METADATA_GAS(
 PREMISE_ID,
 SERVICE_POINT_ID,
 SERVICE_POINT_NUMBER,
 SERVICE_POINT_NAME,
 STREET_NUMBER,
 STREET_NAME,
 TOWN_NAME,
 STATE,
 ZIP_CODE,
 SERVICE_POINT_ADDRESS,
 INSTALLED_AT,
 REMOVED_AT,
 CREATED,
 UPDATED
 ) as (
 select SP.PREMISE_ID
 ,SP.SERVICEPOINT_ID AS SERVICE_POINT_ID
 ,SP.SERVICEPOINT_ID AS SERVICE_POINT_NUMBER
 ,SP.SERVICE_POINT_NAME
 ,SP.STREET_NUMBER
 ,SP.STREET_NAME
 ,SP.TOWN_NAME
 ,SP.STATE
 ,SP.ZIP_CODE
 ,SP.SERVICE_POINT_ADDRESS
 ,SP.SERVICE_POINT_START_DT as INSTALLED_AT
 ,SP.SERVICE_POINT_END_DT as REMOVED_AT
 ,CURRENT_TIMESTAMP as CREATED
 from &GDM_DB.&GDA_SCHEMA.VW_IEDR_GAS_METER_SERVICEPOINT SP
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON SP.PREMISE_ID = C.KY_PREM_NO
 where SP.STATE = 'NY' AND C.CD_PREM_STAT = '02'
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14);
 create or replace view VW_IEDR_SERVICE_POINT_TO_METER_ELECTRIC(
 SERVICE_POINT_NUMBER,
 PREMISE_ID,
 METER_ID,
 START_TIME,
 END_TIME
 ) as (
 select M.GIS_SERVICE_ID AS SERVICE_POINT_NUMBER,PREMISE_NUMBER as PREMISE_ID, M.METER_NUMBER AS
METER_ID, M.INSTALLED_AT AS START_TIME, M.REMOVED_AT AS END_TIME
 from &EDM_DB.&EDA_SCHEMA.METER_TO_PREMISE M
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON M.PREMISE_NUMBER = C.KY_PREM_NO
 WHERE M.STATE = 'NY' AND C.CD_PREM_STAT = '02' GROUP BY 1,2,3,4,5
 );

 create or replace view VW_IEDR_SERVICE_POINT_TO_METER_GAS(
 SERVICE_POINT_ID,
 PREMISE_ID,
 METER_ID,
 START_TIME,
 END_TIME
 ) as (
 select SP.SERVICEPOINT_ID AS SERVICE_POINT_ID,SP.PREMISE_ID,SP.METER_ID,SP.
meter_connection_start_time as START_TIME,SP.METER_CONNECTION_END_TIME as END_TIME
 from &GDM_DB.&GDA_SCHEMA.VW_IEDR_GAS_METER_SERVICEPOINT SP
 JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE C ON SP.PREMISE_ID = C.KY_PREM_NO
 GROUP BY 1,2,3,4,5);

 create or replace view VW_IEDR_USER_TO_ACCOUNT(
 BILLING_ACCOUNT_NBR,
 CUSTOMER_ID,
 USER_ID
 ) as (
 SELECT
 C.KY_BA AS BILLING_ACCOUNT_NBR,
 C.KY_CUST_NO AS CUSTOMER_ID,
 case when TRIM(B.tx_prof_email) is null then ' ' else TRIM(B.tx_prof_email) end as User_ID
 FROM &CDP_DB.&CSS_CDP_SCHEMA.CU01TB01_SAD C
 LEFT OUTER JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU16TB04_PROF_BA A ON A.KY_BA = C.KY_BA
 LEFT OUTER JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU16TB02_PROFILE B ON A.KY_PROFILE_ID = B.KY_PROFILE_ID
 LEFT OUTER JOIN &CDP_DB.&CSS_CDP_SCHEMA.CU04TB01_PREMISE D ON C.KY_PREM_NO = D.KY_PREM_NO
 WHERE D.CD_PREM_STAT = '02' AND TRIM(C.AD_SERV_ST) = 'NY'
 AND (B.cd_profile_type='W' or B.ky_profile_id is null) and (A.cd_stat=2 or A.ky_ba is null)
GROUP BY 1,2,3);