 /*Using hash command to check for duplicates in a snowflake table*/


 SELECT HASH(*), COUNT(*) AS COUNT FROM "PROD_CDP_DB"."APPINSIGHTS_CDP"."APP_INSIGHTS_AUDIT"
GROUP BY 1 HAVING COUNT(*)>1 ORDER BY 2 DESC;

 SELECT HASH(*), COUNT(*) AS COUNT FROM
"PROD_CDP_DB"."APPINSIGHTS_CDP"."APP_INSIGHTS_AVAILIBILITY_RESULTS" GROUP BY 1 HAVING COUNT(*)>5;
 SELECT * FROM (SELECT hash(*) AS RST,* FROM
"PROD_CDP_DB"."APPINSIGHTS_CDP"."APP_INSIGHTS_AVAILIBILITY_RESULTS")where RST =
1855556480569450851;

 SELECT * FROM (SELECT hash(*) AS RST,* FROM
"PROD_CDP_DB"."APPINSIGHTS_CDP"."APP_INSIGHTS_AUDIT")where RST = 8330793176569571732;

 SELECT * FROM (SELECT hash(*) AS RST,* FROM
"PROD_CDP_DB"."APPINSIGHTS_CDP"."APP_INSIGHTS_AUDIT")where RST = -7881980862974780201;